import { DemoUser, FancyNumberItem, AnyApplication, StoredDocument, ChallanRecord, FastagAccount } from './types';

export const DEMO_USERS: DemoUser[] = [
  {
    id: 'user-vikram',
    name: 'Vikramaditya Sharma',
    email: 'vikram.sharma@demo.gati.in',
    phone: '+91 98450 18234',
    role: 'EV Tech Pioneer & Private Owner',
    avatar: 'VS',
    city: 'Bengaluru',
    state: 'Karnataka (KA)',
    aadhaarMasked: 'XXXX-XXXX-4829',
    panMasked: 'ABGPS****K',
    bio: 'Owns a Nexon EV LR & Ather 450X. Frequent expressway commuter.',
    vehiclesCount: 2,
    activePermitsCount: 0,
  },
  {
    id: 'user-priya',
    name: 'Priya Sundaram',
    email: 'priya.logistics@demo.gati.in',
    phone: '+91 94440 92381',
    role: 'Logistics Fleet Director',
    avatar: 'PS',
    city: 'Chennai',
    state: 'Tamil Nadu (TN)',
    aadhaarMasked: 'XXXX-XXXX-9102',
    panMasked: 'CPTPS****M',
    bio: 'Manages a fleet of 18 interstate commercial container vehicles.',
    vehiclesCount: 18,
    activePermitsCount: 6,
  },
  {
    id: 'user-arjun',
    name: 'Arjun Singhania',
    email: 'arjun.singhania@demo.gati.in',
    phone: '+91 98200 44102',
    role: 'Luxury Vehicle Collector',
    avatar: 'AS',
    city: 'Mumbai',
    state: 'Maharashtra (MH)',
    aadhaarMasked: 'XXXX-XXXX-7731',
    panMasked: 'APLSN****F',
    bio: 'Collector of performance GTs and bespoke vintage cruisers.',
    vehiclesCount: 5,
    activePermitsCount: 0,
  },
  {
    id: 'user-ananya',
    name: 'Ananya Deshmukh',
    email: 'ananya.deshmukh@demo.gati.in',
    phone: '+91 97630 11984',
    role: 'First-time Applicant & Student',
    avatar: 'AD',
    city: 'Pune',
    state: 'Maharashtra (MH)',
    aadhaarMasked: 'XXXX-XXXX-3349',
    panMasked: 'BPGPD****Q',
    bio: 'Applied for dual LMV and MCWG learner driving licences.',
    vehiclesCount: 1,
    activePermitsCount: 0,
  },
  {
    id: 'user-rajeshwar',
    name: 'Rajeshwar Verma',
    email: 'rajeshwar.tours@demo.gati.in',
    phone: '+91 98110 55670',
    role: 'Interstate Tourist Bus Operator',
    avatar: 'RV',
    city: 'New Delhi',
    state: 'Delhi (DL)',
    aadhaarMasked: 'XXXX-XXXX-6512',
    panMasked: 'ALFPV****Z',
    bio: 'Runs premium sleeper coaches on Delhi-Manali and Delhi-Jaipur routes.',
    vehiclesCount: 8,
    activePermitsCount: 8,
  },
  {
    id: 'user-kavita',
    name: 'Kavita Menon',
    email: 'kavita.menon@demo.gati.in',
    phone: '+91 98470 33819',
    role: 'Urban Commuter & Designer',
    avatar: 'KM',
    city: 'Kochi',
    state: 'Kerala (KL)',
    aadhaarMasked: 'XXXX-XXXX-8821',
    panMasked: 'BKPMN****L',
    bio: 'Renewing smart registration card for her electric scooter.',
    vehiclesCount: 1,
    activePermitsCount: 0,
  },
  {
    id: 'user-gurpreet',
    name: 'Gurpreet Singh',
    email: 'gurpreet.freight@demo.gati.in',
    phone: '+91 98760 12390',
    role: 'Heavy Freight Transporter',
    avatar: 'GS',
    city: 'Chandigarh',
    state: 'Punjab (PB)',
    aadhaarMasked: 'XXXX-XXXX-1994',
    panMasked: 'CGPSG****H',
    bio: 'Operates multi-axle freight carriers on the Golden Quadrilateral.',
    vehiclesCount: 12,
    activePermitsCount: 12,
  },
  {
    id: 'user-rohan',
    name: 'Rohan Banerjee',
    email: 'rohan.banerjee@demo.gati.in',
    phone: '+91 98300 78219',
    role: 'Vintage Vehicle Restorer',
    avatar: 'RB',
    city: 'Kolkata',
    state: 'West Bengal (WB)',
    aadhaarMasked: 'XXXX-XXXX-4401',
    panMasked: 'AEPPB****E',
    bio: 'Restoring 1968 Royal Enfield Bullet and seeking period registration.',
    vehiclesCount: 3,
    activePermitsCount: 0,
  },
  {
    id: 'user-meera',
    name: 'Meera Joshi',
    email: 'meera.mobility@demo.gati.in',
    phone: '+91 98250 67104',
    role: 'Urban EV Cab Fleet Partner',
    avatar: 'MJ',
    city: 'Ahmedabad',
    state: 'Gujarat (GJ)',
    aadhaarMasked: 'XXXX-XXXX-5529',
    panMasked: 'AFMPJ****R',
    bio: 'Managing 25 clean-fuel city cabs across Gandhinagar and Ahmedabad.',
    vehiclesCount: 25,
    activePermitsCount: 25,
  },
  {
    id: 'user-aman',
    name: 'Amanullah Khan',
    email: 'aman.khan@demo.gati.in',
    phone: '+91 98490 88231',
    role: 'Global Consultant & Traveler',
    avatar: 'AK',
    city: 'Hyderabad',
    state: 'Telangana (TS)',
    aadhaarMasked: 'XXXX-XXXX-2210',
    panMasked: 'BAPAK****Y',
    bio: 'Processing International Driving Permit (IDP) for European trip.',
    vehiclesCount: 1,
    activePermitsCount: 0,
  }
];

export const STATES_AND_RTOS: Record<string, { name: string; rtos: { code: string; name: string }[] }> = {
  'KA': {
    name: 'Karnataka',
    rtos: [
      { code: 'KA-01', name: 'Bengaluru Central (Koramangala)' },
      { code: 'KA-03', name: 'Bengaluru East (Indiranagar)' },
      { code: 'KA-04', name: 'Bengaluru North (Yeshwanthpur)' },
      { code: 'KA-05', name: 'Bengaluru South (Jayanagar)' },
      { code: 'KA-51', name: 'Bengaluru Electronic City' },
      { code: 'KA-09', name: 'Mysuru Urban' }
    ]
  },
  'MH': {
    name: 'Maharashtra',
    rtos: [
      { code: 'MH-01', name: 'Mumbai Central (Tardeo)' },
      { code: 'MH-02', name: 'Mumbai West (Andheri)' },
      { code: 'MH-03', name: 'Mumbai East (Wadala)' },
      { code: 'MH-12', name: 'Pune City' },
      { code: 'MH-14', name: 'Pimpri-Chinchwad' },
      { code: 'MH-43', name: 'Navi Mumbai (Vashi)' }
    ]
  },
  'DL': {
    name: 'Delhi NCR',
    rtos: [
      { code: 'DL-01', name: 'North Delhi (Mall Road)' },
      { code: 'DL-03', name: 'South Delhi (Sheikh Sarai)' },
      { code: 'DL-04', name: 'West Delhi (Janakpuri)' },
      { code: 'DL-07', name: 'South West (Dwarka)' },
      { code: 'DL-10', name: 'Central Delhi (Raja Garden)' }
    ]
  },
  'TN': {
    name: 'Tamil Nadu',
    rtos: [
      { code: 'TN-01', name: 'Chennai Central (Ayanavaram)' },
      { code: 'TN-07', name: 'Chennai South (Thiruvanmiyur)' },
      { code: 'TN-09', name: 'Chennai West (K.K. Nagar)' },
      { code: 'TN-38', name: 'Coimbatore North' }
    ]
  },
  'TS': {
    name: 'Telangana',
    rtos: [
      { code: 'TS-09', name: 'Hyderabad Central (Khairatabad)' },
      { code: 'TS-10', name: 'Secunderabad' },
      { code: 'TS-07', name: 'Ranga Reddy (Attapur)' },
      { code: 'TS-08', name: 'Medchal-Malkajgiri' }
    ]
  },
  'GJ': {
    name: 'Gujarat',
    rtos: [
      { code: 'GJ-01', name: 'Ahmedabad (Subhash Bridge)' },
      { code: 'GJ-27', name: 'Ahmedabad East (Vastral)' },
      { code: 'GJ-05', name: 'Surat City' },
      { code: 'GJ-18', name: 'Gandhinagar' }
    ]
  },
  'UP': {
    name: 'Uttar Pradesh',
    rtos: [
      { code: 'UP-16', name: 'Noida (Gautam Buddha Nagar)' },
      { code: 'UP-14', name: 'Ghaziabad' },
      { code: 'UP-32', name: 'Lucknow Central' },
      { code: 'UP-78', name: 'Kanpur Nagar' }
    ]
  }
};

export const MOCK_FANCY_NUMBERS: FancyNumberItem[] = [
  {
    id: 'fn-0001',
    number: '0001',
    series: 'KA 01 MX',
    fullPlateText: 'KA 01 MX 0001',
    category: 'Super VIP',
    price: 350000,
    state: 'Karnataka (KA)',
    rto: 'KA-01 (Bengaluru Central)',
    numerologySum: 1,
    tag: 'Crown Jewel',
    isPopular: true,
    bidsCount: 14,
    auctionEndsIn: '18h 42m'
  },
  {
    id: 'fn-0007',
    number: '0007',
    series: 'MH 02 CZ',
    fullPlateText: 'MH 02 CZ 0007',
    category: 'Super VIP',
    price: 185000,
    state: 'Maharashtra (MH)',
    rto: 'MH-02 (Mumbai West)',
    numerologySum: 7,
    tag: 'Iconic Seven',
    isPopular: true,
    bidsCount: 22,
    auctionEndsIn: '6h 15m'
  },
  {
    id: 'fn-0786',
    number: '0786',
    series: 'DL 03 CA',
    fullPlateText: 'DL 03 CA 0786',
    category: 'Auspicious',
    price: 125000,
    state: 'Delhi NCR',
    rto: 'DL-03 (South Delhi)',
    numerologySum: 3,
    tag: 'Auspicious Blessed',
    isPopular: true,
    bidsCount: 9,
    auctionEndsIn: '1d 04h'
  },
  {
    id: 'fn-1111',
    number: '1111',
    series: 'TS 09 EZ',
    fullPlateText: 'TS 09 EZ 1111',
    category: 'Quad Mirror',
    price: 95000,
    state: 'Telangana (TS)',
    rto: 'TS-09 (Hyderabad Central)',
    numerologySum: 4,
    tag: 'Quad Perfection',
    isPopular: true,
    bidsCount: 8,
    auctionEndsIn: '2d 12h'
  },
  {
    id: 'fn-7777',
    number: '7777',
    series: 'KA 03 NB',
    fullPlateText: 'KA 03 NB 7777',
    category: 'Quad Mirror',
    price: 110000,
    state: 'Karnataka (KA)',
    rto: 'KA-03 (Bengaluru East)',
    numerologySum: 1,
    tag: 'Quad Lucky',
    isPopular: true,
    bidsCount: 17,
    auctionEndsIn: '14h 30m'
  },
  {
    id: 'fn-9999',
    number: '9999',
    series: 'MH 12 PA',
    fullPlateText: 'MH 12 PA 9999',
    category: 'Quad Mirror',
    price: 150000,
    state: 'Maharashtra (MH)',
    rto: 'MH-12 (Pune Central)',
    numerologySum: 9,
    tag: 'Highest Single Digit',
    isPopular: true,
    bidsCount: 19,
    auctionEndsIn: '9h 10m'
  },
  {
    id: 'fn-0099',
    number: '0099',
    series: 'GJ 01 EA',
    fullPlateText: 'GJ 01 EA 0099',
    category: 'Milestone',
    price: 45000,
    state: 'Gujarat (GJ)',
    rto: 'GJ-01 (Ahmedabad)',
    numerologySum: 9,
    tag: 'Century Minus One',
    isPopular: false,
    bidsCount: 4,
    auctionEndsIn: '3d 08h'
  },
  {
    id: 'fn-1234',
    number: '1234',
    series: 'TN 07 AQ',
    fullPlateText: 'TN 07 AQ 1234',
    category: 'Sequence',
    price: 65000,
    state: 'Tamil Nadu (TN)',
    rto: 'TN-07 (Chennai South)',
    numerologySum: 1,
    tag: 'Ascending Ladder',
    isPopular: true,
    bidsCount: 11,
    auctionEndsIn: '1d 18h'
  },
  {
    id: 'fn-8055',
    number: '8055',
    series: 'DL 01 NX',
    fullPlateText: 'DL 01 NX 8055',
    category: 'Milestone',
    price: 85000,
    state: 'Delhi NCR',
    rto: 'DL-01 (North Delhi)',
    numerologySum: 9,
    tag: 'BOSS Plate Pattern',
    isPopular: true,
    bidsCount: 26,
    auctionEndsIn: '4h 50m'
  },
  {
    id: 'fn-0009',
    number: '0009',
    series: 'UP 16 DX',
    fullPlateText: 'UP 16 DX 0009',
    category: 'Super VIP',
    price: 140000,
    state: 'Uttar Pradesh (UP)',
    rto: 'UP-16 (Noida)',
    numerologySum: 9,
    tag: 'Pure Nine',
    isPopular: true,
    bidsCount: 13,
    auctionEndsIn: '2d 02h'
  }
];

export const MOCK_CHALLANS: ChallanRecord[] = [
  {
    id: 'ch-001',
    challanNumber: 'CH-DL-2026-981024',
    vehicleNumber: 'DL 01 AA 9481',
    violationType: 'Speed Violation (Automated Speed Radar)',
    actSection: 'Section 183(1) Motor Vehicles Act',
    date: '2026-08-22 14:32 IST',
    location: 'Delhi-Meerut Expressway KM 18.4 (Ghazipur Stretch)',
    city: 'New Delhi',
    amount: 2000,
    status: 'PENDING',
    photoEvidenceUrl: '/images/hero-expressway.jpg',
    detectedSpeed: '94 km/h',
    speedLimit: '70 km/h',
    courtNoticeDate: '15-SEP-2026'
  },
  {
    id: 'ch-002',
    challanNumber: 'CH-KA-2026-441209',
    vehicleNumber: 'KA 01 EK 4920',
    violationType: 'Red Light Jump (RLVD Sensor Camera)',
    actSection: 'Section 184(c) Dangerous Driving',
    date: '2026-08-19 09:15 IST',
    location: 'Sony World Junction, Koramangala 80ft Road',
    city: 'Bengaluru',
    amount: 1000,
    status: 'PENDING',
    photoEvidenceUrl: '/images/luxury-plate.jpg',
    courtNoticeDate: '10-SEP-2026'
  },
  {
    id: 'ch-003',
    challanNumber: 'CH-MH-2026-773192',
    vehicleNumber: 'MH 02 CZ 0007',
    violationType: 'Non-Designated Lane / Heavy Vehicle Overtake',
    actSection: 'Section 177 CMVR Lane Discipline',
    date: '2026-08-15 18:40 IST',
    location: 'Mumbai-Pune Expressway, Khandala Ghat Tunnel Exit',
    city: 'Mumbai / Pune',
    amount: 500,
    status: 'PAID',
    photoEvidenceUrl: '/images/permit-transport.jpg',
    paymentRef: 'TXN-GATI-9482014'
  }
];

export const MOCK_FASTAG: FastagAccount = {
  tagId: '34161FA8209418290481',
  vehicleNumber: 'KA 01 EK 4920',
  walletBalance: 190,
  issuingBank: 'ICICI Bank NETC FASTag',
  status: 'LOW_BALANCE',
  recentTolls: [
    { plazaName: 'Navayuga Electronic City Elevated Toll Plaza', date: '25 Aug 08:30 AM', amount: 95, lane: 'Lane 04 FASTag FastPass' },
    { plazaName: 'Attibele Border Toll Plaza (KA-TN)', date: '24 Aug 06:15 PM', amount: 130, lane: 'Lane 02 Dedicated ETC' },
    { plazaName: 'Sheshagirihalli Mysuru Expressway Plaza', date: '22 Aug 11:20 AM', amount: 165, lane: 'Lane 06 Multi-Axle ETC' }
  ]
};

export const MOCK_EXPRESSWAY_ROUTES = [
  {
    name: 'Delhi - Mumbai Expressway (NE-4)',
    distanceKm: 1386,
    totalTollCost: 2450,
    typicalTime: '12h 30m',
    fastagDiscountPercent: 10
  },
  {
    name: 'Mumbai - Pune Yashwantrao Chavan Expressway',
    distanceKm: 94,
    totalTollCost: 320,
    typicalTime: '1h 45m',
    fastagDiscountPercent: 15
  },
  {
    name: 'Bengaluru - Mysuru Expressway (NH-275)',
    distanceKm: 118,
    totalTollCost: 330,
    typicalTime: '1h 15m',
    fastagDiscountPercent: 10
  },
  {
    name: 'Yamuna Expressway (Greater Noida - Agra)',
    distanceKm: 165,
    totalTollCost: 435,
    typicalTime: '2h 00m',
    fastagDiscountPercent: 5
  },
  {
    name: 'Hyderabad Outer Ring Road (ORR Expressway)',
    distanceKm: 158,
    totalTollCost: 260,
    typicalTime: '1h 30m',
    fastagDiscountPercent: 12
  }
];

export const INITIAL_SEED_APPLICATIONS: AnyApplication[] = [
  {
    id: 'app-vl-001',
    referenceNumber: 'GATI-VL-2026-89421',
    serviceType: 'vehicle-licensing',
    title: 'New Vehicle Registration (Nexon EV Empowered+)',
    userId: 'user-vikram',
    applicantName: 'Vikramaditya Sharma',
    phone: '+91 98450 18234',
    email: 'vikram.sharma@demo.gati.in',
    state: 'Karnataka (KA)',
    rtoCode: 'KA-01',
    rtoName: 'Bengaluru Central (Koramangala)',
    status: 'card_generated',
    createdAt: '2026-08-20T10:30:00Z',
    updatedAt: '2026-08-22T14:15:00Z',
    estimatedCompletion: 'Completed',
    currentStepIndex: 5,
    totalSteps: 5,
    nextActionLabel: 'Download Smart RC Card',
    registrationCategory: 'New Private Vehicle',
    vehicleType: 'Electric Vehicle (EV)',
    maker: 'Tata Motors Passenger Vehicles',
    model: 'Nexon EV Empowered+ LR',
    fuelType: 'Electric',
    chassisNumberMasked: 'MAT629472******910',
    engineNumberMasked: 'EV40KWH******88',
    invoiceValue: 1949000,
    roadTaxCalculated: 0,
    greenCess: 0,
    smartCardFee: 450,
    totalFee: 1450,
    registrationNumberAssigned: 'KA 01 EK 4920',
    timeline: [
      { title: 'Application Drafted', description: 'Chassis VIN and invoice uploaded', timestamp: '20 Aug 10:30 AM', completed: true },
      { title: 'Aadhaar e-KYC Verified', description: 'Biometric verification successful', timestamp: '20 Aug 10:34 AM', completed: true },
      { title: 'Statutory Fees Paid', description: '₹1,450 paid via UPI (GatiPay UTR 2608492019)', timestamp: '20 Aug 10:36 AM', completed: true },
      { title: 'RTO Scrutiny Approved', description: 'Physical inspection waived (EV FastTrack)', timestamp: '21 Aug 03:20 PM', completed: true },
      { title: 'Digital Smart RC Minted', description: 'Cryptographic RC Smart Card is live', timestamp: '22 Aug 02:15 PM', completed: true }
    ],
    digitalRcCard: {
      rcNumber: 'KA 01 EK 4920',
      ownerName: 'VIKRAMADITYA SHARMA',
      fatherName: 'RAMANATHA SHARMA',
      address: '#402, Palm Meadows, Whitefield, Bengaluru - 560066',
      modelName: 'TATA NEXON.EV EMPOWERED PLUS LR',
      cubicCapacityOrKw: '106.4 kW (143 BHP)',
      seatingCapacity: 5,
      color: 'Pristine White Dual Tone',
      issueDate: '22-AUG-2026',
      validUpto: '21-AUG-2041',
      financer: 'HDFC BANK AUTO FINANCE',
      chipUid: 'IND-KA01-2026-948102',
      qrData: 'GATI-RC:KA01EK4920:VIKRAMADITYA:EV:VALID_2041'
    }
  },
  {
    id: 'app-fn-002',
    referenceNumber: 'GATI-FN-2026-10492',
    serviceType: 'fancy-numbers',
    title: 'VIP Number Allocation (0007 Series)',
    userId: 'user-arjun',
    applicantName: 'Arjun Singhania',
    phone: '+91 98200 44102',
    email: 'arjun.singhania@demo.gati.in',
    state: 'Maharashtra (MH)',
    rtoCode: 'MH-02',
    rtoName: 'Mumbai West (Andheri)',
    status: 'card_generated',
    createdAt: '2026-08-23T11:00:00Z',
    updatedAt: '2026-08-24T09:40:00Z',
    estimatedCompletion: 'Completed',
    currentStepIndex: 4,
    totalSteps: 4,
    nextActionLabel: 'View Allotment Order',
    selectedNumber: MOCK_FANCY_NUMBERS[1],
    targetVehicleNumber: 'To be assigned on Porsche Taycan GTS',
    chassisNumber: 'WP0ZZZ9JZM******14',
    timeline: [
      { title: 'Choice Number Reserved', description: 'MH 02 CZ 0007 locked for 48 hours', timestamp: '23 Aug 11:00 AM', completed: true },
      { title: 'E-Auction Advance Cleared', description: 'Simulated reserve deposit of ₹1,85,000 paid', timestamp: '23 Aug 11:05 AM', completed: true },
      { title: 'RTO Allotment Approved', description: 'No competing bids during round 1', timestamp: '24 Aug 09:30 AM', completed: true },
      { title: 'Official Allotment Certificate Ready', description: 'Valid for 90 days for vehicle registration', timestamp: '24 Aug 09:40 AM', completed: true }
    ],
    allotmentCertificate: {
      allotmentId: 'ALLOT-MH02-2026-0007',
      allocatedNumber: 'MH 02 CZ 0007',
      series: 'CZ SERIES',
      allotteeName: 'ARJUN SINGHANIA',
      rtoJurisdiction: 'RTO Mumbai West, Andheri (W)',
      allotmentDate: '24-AUG-2026',
      validityWindowDays: 90,
      receiptRef: 'TXN-GATI-88391024',
      qrData: 'GATI-VIP:MH02CZ0007:ARJUN_SINGHANIA:VALID_90_DAYS'
    }
  },
  {
    id: 'app-dl-003',
    referenceNumber: 'GATI-DL-2026-44912',
    serviceType: 'driver-licence',
    title: 'Permanent Driving Licence (LMV + MCWG)',
    userId: 'user-ananya',
    applicantName: 'Ananya Deshmukh',
    phone: '+91 97630 11984',
    email: 'ananya.deshmukh@demo.gati.in',
    state: 'Maharashtra (MH)',
    rtoCode: 'MH-12',
    rtoName: 'Pune City',
    status: 'under_review',
    createdAt: '2026-08-24T16:00:00Z',
    updatedAt: '2026-08-25T11:20:00Z',
    estimatedCompletion: 'Slot scheduled for 28 Aug 2026',
    currentStepIndex: 3,
    totalSteps: 5,
    nextActionLabel: 'View ADTT Track Test Pass',
    licenceType: 'Permanent DL (New)',
    vehicleClasses: ['MCWG (Motorcycle with Gear)', 'LMV (Light Motor Vehicle)'],
    bloodGroup: 'O+ve',
    organDonor: true,
    slotBooking: {
      trackName: 'Automated Driving Test Track (ADTT) Alandi Road',
      slotDate: '28-AUG-2026',
      slotTime: '10:30 AM - 11:30 AM',
      trackAddress: 'IDTR Campus, Alandi Road, Yerawada, Pune - 411006',
      confirmationCode: 'SLOT-MH12-280826-A4'
    },
    timeline: [
      { title: 'Form 2 Application Submitted', description: 'Learner Licence LL-MH12-2026-00481 verified', timestamp: '24 Aug 04:00 PM', completed: true },
      { title: 'Fee Paid & Slot Booked', description: '₹1,350 test and smart card fee settled', timestamp: '24 Aug 04:08 PM', completed: true },
      { title: 'Document Scrutiny Cleared', description: 'Medical certificate Form 1A verified', timestamp: '25 Aug 11:20 AM', completed: true, current: true },
      { title: 'Automated Sensor Track Test', description: 'Scheduled at ADTT Pune on 28 Aug', timestamp: 'Pending', completed: false },
      { title: 'Digital PVC DL Minting', description: 'Issued upon sensor track clearance', timestamp: 'Pending', completed: false }
    ]
  },
  {
    id: 'app-vp-004',
    referenceNumber: 'GATI-VP-2026-90184',
    serviceType: 'vehicle-permit',
    title: 'All India Tourist Permit (AITP 5-Year)',
    userId: 'user-rajeshwar',
    applicantName: 'Rajeshwar Verma',
    phone: '+91 98110 55670',
    email: 'rajeshwar.tours@demo.gati.in',
    state: 'Delhi NCR',
    rtoCode: 'DL-01',
    rtoName: 'North Delhi (Mall Road)',
    status: 'card_generated',
    createdAt: '2026-08-21T09:00:00Z',
    updatedAt: '2026-08-23T15:00:00Z',
    estimatedCompletion: 'Completed',
    currentStepIndex: 5,
    totalSteps: 5,
    nextActionLabel: 'Print National Form 47 Permit',
    permitCategory: 'All India Tourist Permit (AITP)',
    vehicleRegNumber: 'DL 01 AA 9481',
    grossVehicleWeightKg: 16200,
    seatingOrPayload: '42 Seater Luxury AC Sleeper Coach',
    routeCorridors: ['All Indian States & UTs (National Green Corridor)', 'Delhi - Jaipur - Mumbai Corridor', 'Delhi - Manali - Leh Circuit'],
    permitPeriodYears: 5,
    fitnessValidTill: '2027-08-20',
    insuranceValidTill: '2027-08-20',
    puccValidTill: '2027-02-20',
    timeline: [
      { title: 'AITP Application Initiated', description: 'Tourist vehicle chassis & AIS-052 bus code verified', timestamp: '21 Aug 09:00 AM', completed: true },
      { title: 'National Composite Tax Paid', description: '₹18,500 composite single-window fee cleared', timestamp: '21 Aug 09:12 AM', completed: true },
      { title: 'Interstate Clearance Certificate', description: 'MoRTH National Registry synchronization completed', timestamp: '22 Aug 02:00 PM', completed: true },
      { title: 'Form 47 National Permit Live', description: 'QR verifiable across all toll plazas & state borders', timestamp: '23 Aug 03:00 PM', completed: true }
    ],
    digitalPermitDocument: {
      permitNumber: 'AITP-DL-2026-90184-AUTH',
      vehicleNumber: 'DL 01 AA 9481',
      permitHolder: 'RAJESHWAR VERMA / ROYAL RAJPUTANA EXP',
      permitType: 'ALL INDIA TOURIST PERMIT (RULE 85-B)',
      authorizedZones: ['ALL STATES AND UNION TERRITORIES OF INDIA'],
      goodsOrPassengersAllowed: 'PASSENGERS (42 SEATER SLEEPER)',
      issueDate: '23-AUG-2026',
      expiryDate: '22-AUG-2031',
      authRto: 'STA DELHI NCR - SINGLE WINDOW CLEARANCE',
      qrData: 'GATI-PERMIT:AITP90184:DL01AA9481:VALID_2031'
    }
  }
];
